pr:
  -main
jobs:
  - job: Lint
    steps:
      - checkout: self
        fetchDepth: 0
      - task: UsePythonVersion@0
        inputs:
          versionSpec: python.version : '3.12'
        displayName: 'Use Python python.version : '3.12'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
